[workspace]
authors = ["niikun <niikun0209@gmail.com>"]
channels = ["https://prefix.dev/robostack-lyrical","conda-forge"]
name = "zk_accident_forensics"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
sim = "gz sim -r worlds/forensics.sdf"
sim-headless = "gz sim -rs worlds/forensics.sdf"
bridge = "ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=config/bridge.yaml"
policy = {cmd = "./target/debug/policy_node",depends-on = ["build"]}

[dependencies]
ros-lyrical-ros-base = ">=0.13.0,<0.14"
ros-lyrical-ros-gz = ">=3.0.10,<4"
mcap = ">=1.5.0,<2"
pandas = ">=3.0.6,<4"

[activation.env]
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS = "-C link-arg=-Wl,-rpath,$CONDA_PREFIX/lib"

